rm(list=ls(all=TRUE))
library(plyr)
library(ggplot2)
library(ggmap)
library(shiny)
library(bitops)
source('func.R')

cordData = import_cordData()
#saveRDS(cordData,"cordData.RDS")
#cordData = readRDS("cordData.RDS")
regData = import_regData()
#saveRDS(regData,"regData.RDS")
#regData = readRDS("regData.RDS")
regTypeLev = get_Levs(regData[,3])